### ISSUE TITLE
[Feature] Support for Databend

### ISSUE THREAD

**Issue by hantmac** [ScalefreeCOM/datavault4dbt#131]
Hi there, how about adding [Databend](https://github.com/datafuselabs/databend) as it does not seem to be currently supported. The cloud data warehouse of databend is https://app.databend.com.

And I would like to make a pr for it 😄 .

**Comment by tkirschke** [comment]
Hi @hantmac and thanks for reaching out!

Sounds like a great idea! Feel free to open a PR for that and we will review it as soon as we can!

Best regards, 
Tim

**Comment by hantmac** [comment]
> Hi @hantmac and thanks for reaching out!
> 
> Sounds like a great idea! Feel free to open a PR for that and we will review it as soon as we can!
> 
> Best regards, Tim

Hi @tkirschke, thanks for your response! I will working on it and would u like to give me a demo project that using `datavault4dbt` to implement data vault 2.0? And some develop guide of third part warehouse platform may be grate.

**Comment by tkirschke** [comment]
> Hi @tkirschke, thanks for your response! I will working on it and would u like to give me a demo project that using `datavault4dbt` to implement data vault 2.0? And some develop guide of third part warehouse platform may be grate.

Hi @hantmac , 

Check out [this Repository](https://github.com/ScalefreeCOM/datavault4dbt-snowflake-demo)! It is made for Snowflake, but the models inside this repository work with any platform, as soon as you have the TPCH dataset loaded. 

For Development guidelines, there is an existing guide [here ](https://github.com/ScalefreeCOM/datavault4dbt/discussions/60) (check the comment). Hope this helps!
