### ISSUE TITLE
BigQuery Snapshot Control v0

### ISSUE THREAD

**Issue by jon-watson** [ScalefreeCOM/datavault4dbt#134]
An error is thrown when trying to create a snapshot control model in BigQuery.

## Details:

- The version of dbt being used:
  - dbt-bigquery 1.6.7
  - dbt-core 1.6.6
- The version of datavault4dbt being used.
  - 1.1.4
- Steps to reproduce the issue
  1. Set up a dbt project using BigQuery 
  1. Create a model using the example configuration in the docs
  2. execute the dbt run command

The following was the configuration used to reproduce the issue:
{{ config(materialized='incremental') }}

  {%- set yaml_metadata -%}
  start_date: '2015-01-01'
  daily_snapshot_time: '07:30:00'
  {%- endset -%}    

  {%- set metadata_dict = fromyaml(yaml_metadata) -%}

  {%- set start_date = metadata_dict['start_date'] -%}
  {%- set daily_snapshot_time = metadata_dict['daily_snapshot_time'] -%}

  {{ datavault4dbt.control_snap_v0(start_date=start_date,
                                  daily_snapshot_time=daily_snapshot_time) }}

- Any error messages or dbt log files which can give more detail of the problem

The following error message is given by dbt:
Database Error in model xxxxx A valid date part name is required at [55:33]

The following error message is given BigQuery if you execute the dbt compiled SQL in the target/compiled directory:
A valid date part name is required at [44:33]

## Potential solution

The following update to line 58 in file datavault4dbt/macros/tables/bigquery/control_snap_v0.sql appears to resolve this issue:

existing SQL to create the is_end_of_month column:
``` SQL
CASE 
    WHEN LAST_DAY(sdts, 'month') = DATE(sdts) THEN TRUE
    ELSE FALSE
END as is_end_of_month,
```

potential update
``` SQL
CASE 
    WHEN LAST_DAY(DATE(sdts), MONTH) = DATE(sdts) THEN TRUE
    ELSE FALSE
END as is_end_of_month,
```

**Comment by bschlottfeldt** [comment]
Hi, thank you so much for reporting the issue and also contributing with the solution. I'm gonna write a pull request to fix this bug. Will link it here later

**Comment by jon-watson** [comment]
Great, thank you so much.
