### ISSUE TITLE
Ghost record values empty for DATE data type for all supported platforms except exasol

### ISSUE THREAD

**Issue by DataUniversum** [ScalefreeCOM/datavault4dbt#147]
Hi,

In the macro: macros/supporting/ghost_record_per_datatype.sql there are ghost record definition. 

However, in all supported platforms except Exasol, there is not ghost record for DATE data type defined. The effect for this is that any attribute with DATE data type gets NULL value, which is in contrary for ghost record idea.

Snowflake code extract example - no DATE data type:
`{%- if ghost_record_type == 'unknown' -%}
     {%- if datatype in ['TIMESTAMP_NTZ','TIMESTAMP'] %}{{ datavault4dbt.string_to_timestamp(timestamp_format, beginning_of_all_times) }} AS {{ alias }}
     {%- elif datatype in ['STRING', 'VARCHAR'] %}'{{ unknown_value__STRING }}' AS {{ alias }}
     (...)
     {%- elif datatype in ['NUMBER','INT','FLOAT','DECIMAL'] %}0 AS {{ alias }}
     {%- elif datatype == 'BOOLEAN' %}CAST('FALSE' AS BOOLEAN) AS {{ alias }}
     {%- elif datatype == 'ARRAY' %} CAST('{{ unknown_value__STRING }}' as ARRAY) as "{{ alias }}"
     {%- else %}NULL AS {{ alias }}
     {% endif %}`

Is there a reason for it?

Thanks,
Jarek

**Comment by tta-scalefree** [comment]
Hi Jarek,

thanks for raising this! I'm taking a look at it and working on a fix shortly.

Best regards,
Trung
