### ISSUE TITLE
prejoin not working for redshift

### ISSUE THREAD

**Issue by deepak20-a** [ScalefreeCOM/datavault4dbt#149]
The version of dbt being used: 1.1.1
The version of datavault4dbt being used: 1.2.0
Issue in file: datavault4dbt --> macros --> staging --> redshift --> stage.sql
issue in line: 231
issue: below code is used:
left join {{ source(vals['src_name']|string, vals['src_table']) }} as pj_{{loop.index}} on lcte.{{ vals['this_column_name'] }} = pj_{{loop.index}}.{{ vals['ref_column_name'] }}
However, redshift doesn't allow this kind of join. datavault4dbt.multikey should be used to do it properly.

**Comment by deepak20-a** [comment]
![image](https://github.com/ScalefreeCOM/datavault4dbt/assets/48158874/be8fa0ef-6fe4-4a06-85fb-ca91253951ac)

**Comment by thoffmann-sf** [comment]
Hey,

thanks for raising this issue, we are working on a patch for the adapter at the moment, I'll make sure to put this on the agenda. The patch is expected to be released by the 19.01.2024. If you have any further issues or questions we are happy to help

**Comment by thoffmann-sf** [comment]
Hey,

in the newest version of datavault4dbt this issue was fixed
[https://github.com/ScalefreeCOM/datavault4dbt/releases/tag/v1.2.2](url)
