### ISSUE TITLE
Multiactive satellite is not working properly with link

### ISSUE THREAD

**Issue by ShennWooi** [ScalefreeCOM/datavault4dbt#151]
Hi,
We are using link as our hashkey and we are having 'Valid_To' as our ma_attribute. However, there should be only one valid record but there are multiple. Below are the sample of my ma_sat v0 and v1. 

**_ma_sat v0_**
```
{%- set yaml_metadata -%}
source_model: 'source_model'
parent_hashkey: 'hk_key_l'
src_hashdiff: 'hd_sales_ms'
src_ma_key: 'VALID_TO'
src_payload: 
    - field
{%- endset -%}

{%- set metadata_dict = fromyaml(yaml_metadata) -%}

{{
    datavault4dbt.ma_sat_v0(
        source_model=metadata_dict["source_model"],
        parent_hashkey=metadata_dict["parent_hashkey"],
        src_hashdiff=metadata_dict["src_hashdiff"],
        src_ma_key=metadata_dict["src_ma_key"],
        src_payload=metadata_dict["src_payload"],
    )
}}
```

**_ma_sat v1_**
```
{%- set yaml_metadata -%}
sat_v0: 'ma_sat_v0'
hashkey: 'hk_key_l'
hashdiff: 'hd_sales_ms' 
ma_attribute:
    - VALID_TO
ledts_alias: 'ledts'
add_is_current_flag: true
{%- endset -%}    

{%- set metadata_dict = fromyaml(yaml_metadata) -%}

{%- set sat_v0 = metadata_dict["sat_v0"] -%}
{%- set hashkey = metadata_dict["hashkey"] -%}
{%- set hashdiff = metadata_dict["hashdiff"] -%}
{%- set ledts_alias = metadata_dict["ledts_alias"] -%}
{%- set ma_attribute = metadata_dict["ma_attribute"] -%}
{%- set add_is_current_flag = metadata_dict["add_is_current_flag"] -%}

{{
    datavault4dbt.ma_sat_v1(
        sat_v0=sat_v0,
        hashkey=hashkey,
        hashdiff=hashdiff,
        ma_attribute=ma_attribute,
        ledts_alias=ledts_alias,
        add_is_current_flag=add_is_current_flag,
    )
}}

```

Regards,
ShennWooi

**Comment by tkirschke** [comment]
Hi @ShennWooi and thanks for reaching out!

Please provide a minimal source data example to enable reconstructing your scenario. 

Best regards, 
Tim

**Comment by ShennWooi** [comment]
Hi @tkirschke 

The hashkeys for the link are like below:
    - 'ID'
    - 'APPLICATION'
    - 'TYPE'
    - 'GROUP_ID'
    - 'CHANNEL_ID'
    - 'MAT_ID' 
    - 'OFFICE_ID'
    - 'ORG_ID'

There should be only one valid record per mat, group, org / office. Currently there are multiple. 

<html>
<body>
<div class="table-wrap" style="margin: 0px; padding: 0px; color: rgb(23, 43, 77); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
ID | APPLICATION | TYPE | GROUP_ID | CHANNEL_ID | MAT_ID | OFFICE_ID | ORG_ID | VALID_FROM | VALID_TO</br>
0002 | V | Z | 5 | 01 | 123 | 006 | 0001 | 2023-09-03 | 2024-05-31</br>
0001 | V | Z | 5 | 01 | 123 | 006 | 0001 | 2023-04-01 | 2024-05-31</br>
0004 | V | Z | 5 | 01 | 123 | 006 | 0001 | 2023-05-07 | 2024-05-31</br>
0005 | V | Z | 5 | 01 | 123 | 006 | 0001 | 2023-12-05 | 2024-05-31</br>
0003 | V | Z | 5 | 01 | 123 | 006 | 0001 | 2023-06-05 | 2024-05-31</br>

</div><p style="margin: 10px 0px 0px; padding: 0px; color: rgb(23, 43, 77); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"> </p>
</body>
</html>

Regards,
Shenn Wooi
