### ISSUE TITLE
Update PIT implementation in Redshift

### ISSUE THREAD

**Issue by allan-cin** [ScalefreeCOM/datavault4dbt#155]
I see that you are using `COALESCE(LEAD(TIMESTAMP_SUB({{ ldts }}, INTERVAL 1 MICROSECOND))` in PIT for Redshift. However TIMESTAMP_SUB and INTERVAL 1 MICROSECOND are not supported by Redshift.

**Comment by allan-cin** [comment]
also, 
`{%- set hash_dtype = var('datavault4dbt.hash_datatype', 'STRING') -%}`
the default data type should be VARCHAR since STRING is also not supported by redshift

**Comment by thoffmann-sf** [comment]
Hey Allan,

thanks for your feedback, if you've already fixed it yourself feel free to open a PL otherwise we will implement a fix for that in the upcoming release.

Best regards,
Tim
