### ISSUE TITLE
unexpexted-string-literal-inbig-query-staging-macro-because-of-quoted-alias

### ISSUE THREAD

**Issue by tkiehn** [ScalefreeCOM/datavault4dbt#161]
When the staging macro creates ghost records, Big Query returns:
> Syntax error: Unexpected string literal

because the macro quotes the alias for the date datatype in the default__ghost_record_per_datatype macro in macros/supporting/ghost_record_per_datatype.sql

@tta-scalefree @tkirschke This leads to an error in BigQuery because BigQuery does not allow column names with quotes

_Originally posted by @obause in https://github.com/ScalefreeCOM/datavault4dbt/pull/157#discussion_r1555864833_

**Comment by tkiehn** [comment]
Unquoting the alias led to the discovery, that `TO_DATE` is not supported in Big Query and needs to be swapped out with `PARSE_DATE`.
This fixed the error for me.

See: https://cloud.google.com/bigquery/docs/migration/oracle-sql

**Comment by tkirschke** [comment]
Hi @tkiehn, can you open a Pull Request that fixes that issue? You described that you already have a solution, would be great if you can include that in a new PR!
