### ISSUE TITLE
Hash algorithm SHA2 for Snowflake having defined hash_datatype "BINARY(32)" not working as expected

### ISSUE THREAD

**Issue by tkirschke** [ScalefreeCOM/datavault4dbt#165]
### Discussed in https://github.com/ScalefreeCOM/datavault4dbt/discussions/164

<div type='discussions-op-text'>

<sup>Originally posted by **migma-ciklum** April 15, 2024</sup>
We've defined these variables in our dbt_project file (using 1.3.0 version of ScalefreeCOM/datavault4dbt):
-   datavault4dbt.hash: 'SHA2'
-   datavault4dbt.hash_datatype: 'BINARY(32)'

But when running our models against Snowflake, our hash keys and hash diffs will turn out to be BINARY(8388608) instead of BINARY(32). Is there a way to make the hash keys and hash diffs use the defined datavault4dbt.hash_datatype, including the length?

Thanks in advance for your help and feedback!
BR</div>

**Comment by tkiehn** [comment]
Solved by #174 as discussed in https://github.com/ScalefreeCOM/datavault4dbt/discussions/164
