### ISSUE TITLE
LDTS / RSRC naming leads to error (ambiguous column)

### ISSUE THREAD

**Issue by jabibo** [ScalefreeCOM/datavault4dbt#168]
Hi,
I'm using the version 1.3.1. and having trouble to create a stage. It creates an error-message: ambiguous column name 'LDTS' (or RSCR.
I think it is because die attributes are already named like this in the source it is taking both of them...I hadn't had this issue in the version 1.1.0 (which I used before)

Regards
Jan Binge

**Comment by tkiehn** [comment]
Hi Jan,

I have found that in the [dbt_project.yml](https://github.com/ScalefreeCOM/datavault4dbt/blob/19369f72783f1f3379c348fb3cdec9714edb2ee1/dbt_project.yml#L43) the value of the variable [copy_rsrc_ldts_input_columns](https://github.com/ScalefreeCOM/datavault4dbt/wiki/Global-variables#stage-configuration) has changed from `false` to `true`. In the stage.sql-macros the default value is still `false`, but if you copied the variables from the package's changed dbt_project.yml this may have introduced this error. 

Otherwise I think more context could be helpful to address this issue.

Best Regards,
Theo

**Comment by jabibo** [comment]
Hi Theo,

I must apolgize for making such a poor description...
I hope this one is better:
I'm using Snowflake as target-database. There is a load-view on top of a s3-external-table. The load-view is the source for the stage. In the load-view an attribute ldts is being created. The name of the ldts-attribute is lowercase without brackets and set in the stage-yaml: rsrc: 'rsrc'.  copy_rsrc_ldts_input_columns is set to false. While creating the stage the ldts-attribute appears in the source-data-cte and waydown twice in the ldts_rsrc_data-cte...that's where the error appears. I traced the error to this position: in the macro process_columns_to_select (file: stage_processing_macros) the second line is deactivated:
{% set exclude_columns_list = exclude_columns_list | map('upper') | list %}
If activate it - it works...

There is another error I get: In the load-view there is a date-field "edts"which is not being recognized downstream in the SQL. I traced it down to the unknown/error-creation. The aliases are with brackets and in the original uppercase/lowercase-writing..because the edts is lowercase in the yaml it is not recognized.
After I added this line to the macro snowflake__ghost_record_per_datatype (ghost_record_per_datatype)
{%- set alias = alias | string | upper | trim -%}
..it worked..the aliase are now uppercase with brackets which I think is correct for Snowflake...

Hope this helps

Regards
Jan

**Comment by tkirschke** [comment]
Hi @jabibo and thanks for reaching out!

> I traced the error to this position: in the macro process_columns_to_select (file: stage_processing_macros) the second line is deactivated:
> {% set exclude_columns_list = exclude_columns_list | map('upper') | list %}

I can confirm, this line has been accidentally deactivated. I have created a PR that fixes this issue. As soon as that is done, I will create a new Release and let you know here. 



> There is another error I get: In the load-view there is a date-field "edts"which is not being recognized downstream in the SQL. I traced it down to the unknown/error-creation. The aliases are with quotes and in the original uppercase/lowercase-writing..because the edts is lowercase in the yaml it is not recognized.
> After I added this line to the macro snowflake__ghost_record_per_datatype (ghost_record_per_datatype)
> {%- set alias = alias | string | upper | trim -%}
> ..it worked..the aliase are now uppercase with brackets which I think is correct for Snowflake...

Would you be so kind to post your modified "snowflake__ghost_record_per_datatype" macro in here?

Best regards
Tim

**Comment by tkiehn** [comment]
Hi @tkirschke,

while reactivating the line fixes the issue on snowflake I do now get a comparable error in big query: `Unrecognized name: edwLoadDate` which I did not before 1.3.2.

When `macros/staging/<adapter>/stage.sql` selects the columns from the source data in the CTE `ldts_rsrc_data`, the ldts and rsrc get incorrectly selected twice. Once to get renamed to the defined ldts and rsrc names and once named like in the source.
There seems to be an error with the content of `source_columns_to_select`, I am not sure yet where it exactly happens.

After digging around I found, that line 14 `macros/internal/helpers/stage_processing_macros` used to lower the column_names for the exclude_columns_list. After using [the old](https://github.com/ScalefreeCOM/datavault4dbt/blame/98029a88529df7944b54aed2f7f8686de54c9c58/macros/internal/helpers/stage_processing_macros.sql#L14) (1.2.2) line, the error didn't come up again.

When I have more time I can investigate further.

Best Regards,
Theo

**Comment by tkirschke** [comment]
> Hi @tkirschke,
> 
> while reactivating the line fixes the issue on snowflake I do now get a comparable error in big query: `Unrecognized name: edwLoadDate` which I did not before 1.3.2.
> 
> When `macros/staging/<adapter>/stage.sql` selects the columns from the source data in the CTE `ldts_rsrc_data`, the ldts and rsrc get incorrectly selected twice. Once to get renamed to the defined ldts and rsrc names and once named like in the source. There seems to be an error with the content of `source_columns_to_select`, I am not sure yet where it exactly happens.
> 
> After digging around I found, that line 14 `macros/internal/helpers/stage_processing_macros` used to lower the column_names for the exclude_columns_list. After using [the old](https://github.com/ScalefreeCOM/datavault4dbt/blame/98029a88529df7944b54aed2f7f8686de54c9c58/macros/internal/helpers/stage_processing_macros.sql#L14) (1.2.2) line, the error didn't come up again.
> 
> When I have more time I can investigate further.
> 
> Best Regards, Theo

Hi @tkiehn , 

I added adapter specific macros for process_columns_to_select in this branch: https://github.com/ScalefreeCOM/datavault4dbt/tree/tkirschke-patch-3
Snowflake still has the "upper" mapping, but the default macro doesn't have it anymore. That should solve it for BigQuery again, and for Synapse as well @polat-deniz.

Would you be so kind and test this branch?

Best regards
Tim

**Comment by tkiehn** [comment]
Hi @tkirschke,

i tried the branch `tkirschke-patch-3` and I now get a compilation error in a reference table:
```
Compilation Error in model category_r (models\raw_vault\category_r.sql)
  can only concatenate list (not "str") to list
  
  > in macro ref_table (macros\tables\ref_table.sql)
  > called by model category_r (models\raw_vault\category_r.sql)
```

It seems to be a call of `process_columns_to_select` in [macros/table/biquery/ref_table.sql](https://github.com/ScalefreeCOM/datavault4dbt/blob/a6c0bb51e68015b169a770dfcfc9ec697d379dd6/macros/tables/bigquery/ref_table.sql).

Best regards
Theo

**Comment by tkirschke** [comment]
Hi @tkiehn , 

You are right, I forgot to add a "return()" to the adapter.dispatch. No it works for me on Snowflake, I will try on BigQuery as well.

Best regards, 
Tim
