### ISSUE TITLE
dbt_utils dependency upgrade to 0.9.2

### ISSUE THREAD

**Issue by anitsche-bt** [ScalefreeCOM/datavault4dbt#19]
Hi guys, 
like to test your dbt package but i have trouble because all other packages in my current project have been upgraded and now compatibility to dbt-utils 0.9.2. 
Any chance you are able to check if an upgrade of your dependency is possible.

Thanks in advance.

**Comment by tkirschke** [comment]
Hi!
Thanks for your feedback!
The latest release v1.0.1 now includes raised dbt_utils requirements. 
Additionally, dbt Hub installation is now supported, and added to the Readme.md.

I really hope you can start experimenting with datavault4dbt now. 
Looking forward to future feedback!
