### ISSUE TITLE
RedShift Fixed redshift redshift__concattenated_standardise

### ISSUE THREAD

**Issue by thoffmann-sf** [ScalefreeCOM/datavault4dbt#209]
Found a bug in the redshift__concattenated_standardise and fixed it

**Comment by maxmue** [comment]
Good day, @thoffmann-sf! I'm currently implementing DV on Redshift. Is this patch going out any time soon? I'm asking because I believe I will need some fixes from the most recent version but I'm blocked by sticking to this patch.

**Comment by tkiehn** [comment]
Hi @maxmue,

while we can not promise a certain date for the release of the patch rest assured it will happen as soon as possible.
We are working with high pressure on finishing the remaining necessities and are looking forward to release them.

Did you try out installing from the [dev branch](https://github.com/ScalefreeCOM/datavault4dbt/tree/dev) by any chance?

Kind regards
Theo

**Comment by maxmue** [comment]
Thanks, Theo, thanks for the tip. The `dev` branch does work.
