### ISSUE TITLE
CI/CD remote pipeline trigger

### ISSUE THREAD

**Issue by DamianHinz** [ScalefreeCOM/datavault4dbt#215]
The main Pipeline is lying on the ci-cd repo but should be triggered from the public datavault4dbt repo.
Find a way to trigger pipelines from a pipeline of another repository.

**Comment by DamianHinz** [comment]
Done. Can be released as soon as the bug in currently running tests are fixed

**Comment by tkiehn** [comment]
Closing this as the pipeline is working now 
CC: @DamianHinz
