### ISSUE TITLE
sqlserver hub.sql need alias for rsrc_static_query_source

### ISSUE THREAD

**Issue by cjpotgieter** [ScalefreeCOM/datavault4dbt#76]
Hi, I am working on the sqlserver pre-release and in hub.sql if you have a static record source the select syntax is incorrect that gets generated in line 50 - 62
The subquery needs an alias. It only failed on the 2nd load
datavault4dbt\macros\tables\sqlserver\hub.sql

{%- set rsrc_static_query_source -%}
                SELECT count(*) FROM (
                {%- for rsrc_static in rsrc_statics -%}
                    SELECT t.{{ src_rsrc }},
                    '{{ rsrc_static }}' AS rsrc_static
                    FROM {{ this }} t
                    WHERE {{ src_rsrc }} like '{{ rsrc_static }}'
                    {%- if not loop.last %}
                        UNION ALL
                    {% endif -%}
                {%- endfor -%}
                ) sub -- I added this alias to the subquery otherwise it fails
            {% endset %}

**Comment by cjpotgieter** [comment]
Thanks, I was installing directly from the branch. I didn't see details regarding the test releases. Where is the test releases listed?

**Comment by tkirschke** [comment]
Tested it again and with the proposed modification it works flawlessly. Therefore I close this issue!
