### ISSUE TITLE
Snowflake: Link (and nhl?): Link cannot be source from the same stage twice

### ISSUE THREAD

**Issue by jabibo** [ScalefreeCOM/datavault4dbt#82]
Hi, 
I want to create a Link. The source has 3 Fields Key1, Email1, Email2.
The link should be created from Key1 / Email1 and  Key1 / Email2. I created two BK and two Hub-HK from the emails
and two Link-HK containing either email1 or email2.
I get the error that the SQL doesn't find the "normal" hub-hk (without number). It seems that though I created two sources in the link-definition only one is created in the SQL (we had the same issue with hubs)

Regards

**Comment by tkirschke** [comment]
Hi @jabibo and thanks for reaching out!

Loading a multi source entity from the some source multiple times is a known limitation in the current release. 
But it is changed in the upcoming release v1.1! I hope to get this release today or tomorrow. But in case you want to preview this new feature, feel free to directly install from the v1.1 branch, by changing your packages.yml to this: 

```
packages:
  - git: "https://github.com/ScalefreeCOM/datavault4dbt"
    revision: v1.1
```

Let me know if the previewed version fixes your problem!

Kind regards, 
Tim

**Comment by tkirschke** [comment]
Hi @jabibo , 
The new version is released now. We're you already able to test it?
Let me know if we can close this issue 🫡

**Comment by jabibo** [comment]
Hi @tkirschke,

that worked - Thank you...

Regards
