### ISSUE TITLE
incorrect query used in rec_track_sat

### ISSUE THREAD

**Issue by cmettler** [ScalefreeCOM/datavault4dbt#94]
Hi, I've started to get a grip on the code

I think this line 

https://github.com/ScalefreeCOM/datavault4dbt/blob/c170e700505beca8d726eaa423830fe656c1f468/macros/tables/exasol/rec_track_sat.sql#L84

should be run_query(rsrc_static_query_source_count) ?

KR
Christoph

**Comment by tkirschke** [comment]
Hi @cmettler, 

Correct, that should have been "run_query(rsrc_static_query_source_count)". It is implemented like this for the record tracking satellites of all adapters. Will add a corresponding branch to fix this!

Kind Regards
Tim
